scikit-build/scikit-build

skbuild/cmaker.py
skbuild/distutils_wrap.py

The idea is for package writers to develop their packages as if they were pure
python, except with the addition of C/C++ source files scattered where
desired.  The mapping of source files to libraries are provided by
CMakeList.txt files, which must install the libraries within the source
directory; at the locations where the imports in the pure python portions of
the package expect them.
This example follows popular practice for packages featuring a mix of pure and
compiled code.  Most compiled functionality are isolated in self-contained
modules that are built into shared libraries with names starting with an
underscore (_).  These libraries are paired with a pure python module of the
same name sans underscore.  In this module the compiled functionality is
exposed with the desired …

try a package-centric approach

---

docs/installation.rst

Recommend pip over easy_install.  Give instructions for installation from source.
The `pip install` command will not work until an initial package is on PyPI.

Updates to the installation docs

---

HISTORY.rst
setup.py

Improvements when reviewing `setup.py`.
@scikit-build/developers I noticed there was a referenced mailing list that did not exist, so I created it. It is now here:
https://groups.google.com/forum/#!forum/scikit-build
Please let me know when you have signed up, and I will add you as an administrator.

setup.py improvements

---

setup.py

See http://nose.readthedocs.io/en/latest/setuptools_integration.html?highlight=python%20setup.py%20test
Suggested-by: Matt McCormick <matt.mccormick@kitware.com>

setup.py: Fix test command setting 'nose.collector' as test_suite See #58

---

docs/installation.rst

This commit fixes the formatting of the Python package dependencies in the
documentation by including the requirements*.txt files as literal blocks.
Reference:
http://docutils.sourceforge.net/docs/ref/rst/directives.html#including-an-external-document-fragment

documentation: Fix formatting of requirements

---

README.rst
docs/usage.rst
requirements.txt
skbuild/__init__.py
skbuild/cmaker.py
skbuild/command/bdist.py
skbuild/command/bdist_wheel.py
skbuild/command/build.py
skbuild/command/clean.py
skbuild/command/install.py
skbuild/distutils_wrap.py
skbuild/setuptools_wrap.py
tests/__init__.py
tests/exec_2.py
tests/exec_3.py
tests/test_hello.py
tests/test_hello_cython.py
tests/test_outside_project_root.py
tests/test_pen2.py
tests/test_skbuild_variable.py
tests/test_tower_of_babel.py

Building wheels should now work!
Also refactors some of the test code.  Subproject tests (defined in their `CMakeLists.txt` files) are currently commented out.  They will later be replaced with nose-friendly versions.

Switch to setuptools

---

skbuild/cmaker.py
skbuild/exceptions.py
skbuild/setuptools_wrap.py
tests/test_outside_project_root.py

Fixes #75.
Display the following information when a configure or build error occurs:
- The command line in a format that can be copied and pasted into a shell
- The source directory
- The working directory
Given that information, the user can get more details from CMakeCache.txt in the working directory.
Example output (following CMake output) from a configure error:
-- Configuring incomplete, errors occurred!
See also "/home/msmolens/dev/scikit-build/tests/samples/tower-of-babel/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
File "/home/msmolens/dev/scikit-build/skbuild/setuptools_wrap.py", line 136, in setup
cmkr.configure(cmake_args)
File "/home/msmolens/dev/scikit-build/skbuild/cmaker.py", line 157, in configure
os.path.abspath(CMAKE_BUILD_DIR)))
An error occurred …

CMaker: make configure and build errors more informative

---

tests/samples/hello-cython/CMakeLists.txt
tests/samples/hello/CMakeLists.txt
tests/samples/pen2-cython/CMakeLists.txt
tests/samples/tower-of-babel/CMakeLists.txt

They are redundant and only one or the other should be called per best
practices.

tests: Do not call both include(CTest) and enable_testing()

---

.coveragerc
.travis.yml
appveyor.yml
ci/appveyor/driver.py
circle.yml
pytest.ini
requirements-dev.txt
setup.cfg
setup.py
tests/test_platform.py
tox.ini

Because nose is not being maintained, switch from nose to py.test
(http://docs.pytest.org/).
From https://nose.readthedocs.io/en/latest/:
Nose has been in maintenance mode for the past several years and will likely
cease without a new person/team to take over maintainership. New projects should
consider using Nose2, py.test, or just plain unittest/unittest2.
Fixes #91

Switch to py.test testing tool

---

.travis.yml

Allow failures on Linux/Python 3.3 builds until the following Travis CI issue is resolved:
https://github.com/travis-ci/travis-ci/issues/6437

ci/travis: allow failures on Linux/Python 3.3 builds

---

skbuild/cmaker.py
skbuild/command/egg_info.py
skbuild/setuptools_wrap.py
tests/test_command_line.py

Fixes #83 
Note that the scikit-build options are still treated as global options as opposed to build subcommand options. #57 hints that perhaps we want to push some options down into the subcommand.

Improve argument parsing and --help output

---

skbuild/command/__init__.py
skbuild/command/bdist.py
skbuild/command/bdist_wheel.py
skbuild/command/build.py
skbuild/command/clean.py
skbuild/command/egg_info.py
skbuild/command/install.py

Removes code that was duplicated across multiple custom command classes and replaces it with a mixin solution.  Eliminates duplication and should also help with coverage numbers.
One technical challenge is that distutils/setuptools command classes are old-style classes, which don't work with mixins.  This PR addresses the challenge by introducing a small wrapper function that takes an old-style class and produces an equivalent new-style class.
Also, replaces superclass calls with proper uses of `super`.

factor out custom command logic to mixins

---

.travis.yml

Test the fix for https://github.com/travis-ci/travis-ci/issues/6437.

WIP: ci/travis: remove workaround to allow failures on Linux/Python 3.3 builds

---

appveyor.yml
ci/appveyor_driver.py
skbuild/command/egg_info.py
skbuild/command/sdist.py
skbuild/setuptools_wrap.py
tests/test_hello.py
tests/test_hello_cython.py
tests/test_skbuild_variable.py

Implements the `sdist` command for creating source distributions.
Uses the `sdist` command class from *distutils* (not setuptools).
Basically, it works by just jumping ahead of distutils' `sdist` logic and creating a MANIFEST file if the project does not provide its own.
This will only work within a git repo, since the implementation relies on the output of `git ls-files` to determine what files to include in the source distribution.
This implementation makes for some undesirable quirks, such as the output from `python setup.py sdist --help` being incorrect, but should suffice for the main source distribution needs for projects.

Implement source distributions. fixes #84

---

skbuild/setuptools_wrap.py
tests/test_setup.py

Since the implementation of is_pure() in both py2 and py3 is as reported
below, implementation has_ext_modules() is enough to ensure is_pure()
will always return False.
This commit also adds a test (1) checking the type of object returned
by the skbuild.setup and (2) ensuring is_pure() return False
```
def is_pure(self):
return (self.has_pure_modules() and
not self.has_ext_modules() and
not self.has_c_libraries())
```

setuptools_wrap: Remove unneeded "is_pure" method, add test_setup

---

skbuild/platform_specifics/abstract.py

Considering that:
* Check for invalid generator will not raise an exception, instead exit
code of CMake indicates if there was an issue.
* Test for a valid installation of CMake is already done in the CMaker
constructor by invoking "cmake --version" and catching OSError and
CalledProcessError
This commit removes the extra try/catch.

skbuild/CMakePlatform: Remove unneeded subprocess call exception handling

---

skbuild/cmaker.py
skbuild/setuptools_wrap.py
tests/samples/cmakelists-not-in-top-level-dir/hello/CMakeLists.txt
tests/samples/cmakelists-not-in-top-level-dir/hello/__main__.py
tests/samples/cmakelists-not-in-top-level-dir/hello/_hello.cxx
tests/samples/cmakelists-not-in-top-level-dir/setup.py
tests/test_cmakelists_not_in_top_level_dir.py

This PR adds support for a `skbuild.setup` specific keyword `cmake_source_dir`.
If not specified, `CMakeLists.txt` is expected in the current working directory. Alternatively, setting this new keyword to an existing sub-directory of your project will ensure CMake is using it to configure and build.

setuptool_wrap: Add support for 'cmake_source_dir' keyword

---

skbuild/setuptools_wrap.py
tests/test_setup.py

This PR adds support for a `skbuild.setup` specific keyword `cmake_args`.
If specified the arguments will be passed to CMake when it is used to configure the project. Note that if the same CMake arguments are also passed from the command line, they will have priority.

Setup add support cmake args keyword

---

tests/test_cmaker.py

Following d9dda99d, configure parameter has been updated
from 'cmake_src_dir' to 'cmake_source_dir'.

tests: Update variable name used in 'test_make'

---

skbuild/command/egg_info.py
skbuild/command/generate_source_manifest.py
skbuild/command/sdist.py
skbuild/setuptools_wrap.py

This will avoid the generation of MANIFEST when building a Wheel

command: Split source MANIFEST generation into its own command

---

skbuild/resources/cmake/targetLinkLibrariesWithDynamicLookup.cmake

This commit has two purposes:
(1) it fixes logic checking for cross-compilation (the regression
was introduced by scikit-build/scikit-build#51 and scikit-build/scikit-build#47
(2) It configure the text project setting CMAKE_ENABLE_EXPORTS to ON. Doing
so ensure the executable compiled in the test exports symbols (if supported
by the underlying platform).
See https://cmake.org/cmake/help/v3.6/prop_tgt/ENABLE_EXPORTS.html?highlight=enable_export

Fix targetLinkLibrariesWithDynamicLookup

---

tests/samples/cmakelists-not-in-top-level-dir/hello/CMakeLists.txt
tests/samples/fail-hello-with-compile-error/CMakeLists.txt
tests/samples/fail-hello-with-compile-error/hello/CMakeLists.txt
tests/samples/hello-cython/CMakeLists.txt
tests/samples/hello-cython/hello/CMakeLists.txt
tests/samples/hello/CMakeLists.txt
tests/samples/hello/hello/CMakeLists.txt

Extra install rules became obsolete after integration the support for
"hybrid project" (See 0d0ddbf)
File copy are removed because testing within the samples project should
be done using a pythonic testing framework (e.g pytest)

tests/samples: Simplify project removing unneeded install rules and file copy

---

.travis.yml
appveyor.yml
circle.yml
scikit-ci.yml

* Update PATH and remove use of $<PYTHON>
* Remove explicit setting of RUN_ENV to an empty var (not needed following
scikit-build/scikit-ci@e48e300)
* upgrade of pip still requires to be invoked using "python -m pip",
otherwise, windows complains that it can't remove "pip.exe"
scikit-ci:
```bash
$ git shortlog 0.7.0..0.12.0 --no-merges
Jean-Christophe Fillion-Robin (22):
Bump version to 0.8.0
ci: Install scikit-ci-addons into addons directory
tests/test_current_service: Test for invalid service
coverage: ci/__main__: Fix report removing exclusion from coveragerc
tests/test_current_service: Fix test when running on CI service
setup: Add "Environment :: Console" classifier
setup: Simplify release process using "versioneer"
ci: Display normal error message when command fails while executing …
```

ci: Update scikit-ci[-addons] and simplify "scikit-ci.yml"

---

.travis.yml
appveyor.yml
circle.yml
scikit-ci.yml

```
$ git shortlog 0.10.0..0.11.0 --no-merges
Jean-Christophe Fillion-Robin (6):
docs/make_a_release: Re-order steps to account for use of versioneer
docs/make_a_release: Ensure uploaded distributions are signed
docs/make_a_release: Update reference to external documentation
docs/addons: Fix typo in enable-worker-remote-access section
addon/install_pyenv: Use PYTHON_VERSION instead of PYTHONVERSION
addon/install_pyenv: Skip brew update/upgrade if python if found in the cache
```

travis/install_pyenv: Improve MacOSX build time updating scikit-ci-addons

---

tests/test_utils.py

This commit increases the robustness of the test and should ensure
it pass when executed on conda-forge ci.
See https://github.com/conda-forge/staged-recipes/pull/1989
Suggested-by: Isuru Fernando <isuruf@gmail.com>

tests: Improve "push_dir" tests to not rely on build directory name

---

CHANGES.rst
requirements.txt

As suggested by @mivade: "Considering the target audience is likely using
anaconda/miniconda, I would think the most sensible thing is to use the
version used there as the minimum version. A quick check indicates that
setuptools is at version 28.8 there, so I think requiring >=28.0.0 should
work."
See #212, pypa/pip#2751 and ContinuumIO/anaconda-issues#542
Suggested-by: "Michael V. DePalatis" <mike@depalatis.net>

requirements: unpin version of setuptools and require >= 28.0.0

---

skbuild/cmaker.py

Because calling `sysconfig.get_config_var('multiarchsubdir')` returns an empty string on Linux, `du_sysconfig` is only used to get the value of `LIBDIR`.
This commit fixes a regression introduced in b8f5572 (skbuild: Fix build within virtualenv on windows)
See #219

skbuild.cmaker: Fix cmaker.get_python_library on multi-arch Linux distribution

---

skbuild/resources/cmake/targetLinkLibrariesWithDynamicLookup.cmake

When CMake ran multiple time, the value would change from the correct
string to a boolean value. This caused failure of the expected dynamic
lookup behavior.
This patch addresses #240

Correct DYNAMIC_LOOKUP_* cache type to STRING

---

skbuild/resources/cmake/UseCython.cmake

spaces in CYTHON_FLAGS are incorrectly escaped (at least on linux) when provided as command line arguments to the cython executable through CMake cache entries.
Here is a simple mwe (run `$ bash build.sh` in a terminal)
**build.sh**
```bash
#!/usr/bin/env bash
rm -r build; mkdir -p build; cd build
cmake \
-DCYTHON_FLAGS='-X boundscheck=False -X wraparound=False' \
-DCMAKE_MODULE_PATH="$SKBUILD_PREFIX/skbuild/resources/cmake" \
-DCMAKE_VERBOSE_MAKEFILE=ON ..
make || exit 1
python3 -c 'import fib; fib.fib(2000)'
```
**CMakeLists.txt**
```CMake
cmake_minimum_required(VERSION 3.8)
project(fib)
find_package(Cython REQUIRED)
include(UseCython)
include_directories(${PYTHON_INCLUDE_DIRS})
add_cython_target(fib fib.pyx C PY3)
add_library(fib MODULE fib.c)
set_target_properties(fib PROPERTIES …
```

avoid escaping spaces

---

CHANGES.rst
docs/cmake-modules.rst
docs/cmake-modules/F2PY.rst
skbuild/resources/cmake/FindF2PY.cmake
skbuild/resources/cmake/FindPythonExtensions.cmake

From https://github.com/scikit-build/scikit-build/pull/273#issuecomment-362862052:
So the idea here is actually to eliminate `numpy.distutils` entirely over time and replace it with scikit-build. We can't do that if we write `f2py -c` because `numpy.distutils` is still used. Instead we want to use `f2py` to generate the C files and then link them to the Python extension.
I'm also not happy with the way that Cython support was implemented in scikit-build. Ideally, you would be able to write the following and have scikit-build autogenerate the cython and f2py targets:
```
add_library(LIBRARY_NAME
input.pyf.src
input.pyx
) 
```
If you look at [what we're replacing](https://github.com/scipy/scipy/blob/5531da38cec429f3cf2f9aca0f698e2130562592/scipy/fftpack/setup.py), we essentially need to …

Find f2py rebased

---

.gitignore
CHANGES.rst
Makefile
skbuild/command/egg_info.py
skbuild/command/test.py
skbuild/setuptools_wrap.py
tests/__init__.py
tests/samples/issue-274-support-default-package-dir/CMakeLists.txt
tests/samples/issue-274-support-default-package-dir/hello_tests/__init__.py
tests/samples/issue-274-support-default-package-dir/setup.py
tests/samples/issue-274-support-default-package-dir/src/hello/__init__.py
tests/test_issue274_support_default_package_dir.py

This commit supports specifying a default directory for all packages
that do not have one already explicitly associated with them.
See #274

setuptools_wrap: Add support for default package_dir

---

.codecov.yml
CHANGES.rst

This commit will prevent PR check from reporting failure when coverage
only slightly change.
Adapted from https://github.com/NeurodataWithoutBorders/pynwb/pull/496
Thanks: Doruk Ozturk <doruk.ozturk@kitware.com>

ci: Add codecov config file for better defaults

---

CHANGES.rst
skbuild/cmaker.py
tests/test_cmaker.py

Fix cmaker parsing command line arguments in the wrong order when verifying them, as reported in followup to #342.

Fix cmaker parse

---

.coveragerc

This commit fixes the following warning:
--include is ignored because --source is set (include-ignored)

coverage: Fix "include-ignored" warning

---

tests/__init__.py
tests/test_setup.py

This commit fixes error detected with newer version of flake8.

flake8: Fix flake8 error W605 "invalid escape sequence"

---

skbuild/command/build_ext.py
skbuild/setuptools_wrap.py
tests/samples/issue-284-build-ext-inplace/CMakeLists.txt
tests/samples/issue-284-build-ext-inplace/hello/_hello_ext.cxx
tests/samples/issue-284-build-ext-inplace/hello/_hello_sk.cxx
tests/samples/issue-284-build-ext-inplace/setup.py
tests/test_issue284_build_ext_inplace.py

This PR addresses issues (#284 and #352) where command `python setup.py build_ext --inplace` fails when using scikit-build. To allow for running `build_ext`, I wrote a command class following the template I saw in `build` and `build_py`. Unfortunately, this didn't just make the normal `--inplace` option work because the `setuptools.**.build_ext` command only copies registered extension modules, which the cmake outputs are not. To remedy this I simply hacked in a check for `'--inplace' in sys.argv` and then copied the libraries to the source directory as would be done in "developer_mode". 
I'm not 100% this is the best way to implement the feature as (1) setuptools is complex and (2) I'm still getting familiar with how this library works and its standards.

Add support for build_ext and --inplace

---

.travis.yml
CHANGES.rst

See https://devguide.python.org/devcycle/?highlight=end%20of%20life#end-of-life-branches

travis: Remove obsolete Python 3.4 testing

---

CHANGES.rst
requirements-dev.txt
tests/__init__.py
tests/conftest.py
tests/pytest_helpers.py
tests/test_cmakelists_not_in_top_level_dir.py
tests/test_hello_cpp.py
tests/test_hello_cython.py
tests/test_hello_pure.py
tests/test_include_exclude_data.py
tests/test_issue335_support_cmake_source_dir.py
tests/test_manifest_in.py
tests/test_utils.py

To allow pytest to display useful information, the tests containing
the helper function is registered.
See https://docs.pytest.org/en/latest/writing_plugins.html#assertion-rewriting

test: Fix reporting of assert associated with check_wheel_content

---

CHANGES.rst
docs/index.rst
docs/notes.rst
skbuild/resources/cmake/FindPythonExtensions.cmake
tests/__init__.py
tests/test_hello_cpp.py
tests/test_hello_cython.py
tests/test_issue284_build_ext_inplace.py

FindPythonExtensions: Fix deprecated warning and use correct python extension suffix on windows

---

CHANGES.rst
docs/generators.rst
skbuild/constants.py
tests/test_issue342_cmake_osx_args_in_setup.py

If the variable is defined, use it. Othewise use the value from distutils.

Use the MACOSX_DEPLOYMENT_TARGET env variable

---

CHANGES.rst
skbuild/resources/cmake/FindF2PY.cmake

See #449
Co-authored-by: Ben <code@bnavigator.de>

FindF2PY: Ensure python version specific of f2py executable is looked up first

---

CHANGES.rst
skbuild/cmaker.py

We are using `scikit-build` in https://github.com/skvark/opencv-python. When something goes wrong, we need to run the exact same CMake invocation with tracing to diagnose. This PR adds printing of it.
Instead of printing the raw argv, [`shlex.join`](https://docs.python.org/3.8/library/shlex.html?highlight=shlex#shlex.join) could be used to produce a copypasteable cmdline. But it's 3.8+

Print configuration CMake command line

---

requirements.txt
skbuild/platform_specifics/linux.py

`platform.linux_distribution()` was removed in Python 3.8. Move to `distro.id()`

Replace linux_distribution() missing in Python 3.8

---

skbuild/cmaker.py

Looking at the diff of https://github.com/scikit-build/scikit-build/commit/1c11225560cdefff592cdfd71c9d4f3777765606 it appears that DeMorgan's law bit us here. The net result is that scikit build works if the location of python.h pointed to by sysconfig is accurate, but in a cross-compile type scenario Python.h may be incorrectly marked as found.

Fix bug in python.h lookup logic.

---

CHANGES.rst
docs/usage.rst
requirements.txt
skbuild/setuptools_wrap.py
tests/__init__.py
tests/samples/issue-335-support-cmake-source-dir/wrapping/python/CMakeLists.txt
tests/samples/test-filter-manifest/CMakeLists.txt
tests/samples/test-filter-manifest/wrapping/python/CMakeLists.txt
tests/samples/test-filter-manifest/wrapping/python/setup.py
tests/test_filter_manifest.py
tests/test_issue335_support_cmake_source_dir.py

This is a simple hook to enable custom processing of the cmake manifest before producing the wheel.
The goal for us is to drop static binaries of dependencies, as well as their headers, and other artefacts such as cmake files, as we want the wheel to only include what is required at runtime.
I am using this here: https://github.com/jupyter-xeus/xeus-python-wheel/pull/36
Fixes #473

Add hook to process manifest

---

CHANGES.rst
skbuild/platform_specifics/platform_factory.py

platform_factory: Lazily import platform to support disto<1.2.0

---

CHANGES.rst
skbuild/setuptools_wrap.py

So that setuptools won't complain about unknown setup options.

setuptools_wrap: Remove cmake_process_manifest_hook keyword from argument dict

---

docs/usage.rst

Change `cmake_manifest_process_hook` to `cmake_process_manifest_hook`.
I got confused by this when I was trying to address https://github.com/uber/h3-py/issues/125

typo in cmake_process_manifest_hook

---

CHANGES.rst
skbuild/cmaker.py

I believe this should hide the warning whenever SKBUILD is not checked in the CMake files. It also isn't a user-facing variable (that is, users don't set it).

fix: hide warning if SKBUILD is not used

---

appveyor.yml

Follow the release of python 2.7 wheels on pypi for ruamel-ordereddict
package, this commit reverts eb1759376 (ci: Attempt to fix appveyor
failure)
References:
* https://sourceforge.net/p/ruamel-ordereddict/tickets/14/
* https://pypi.org/project/ruamel.ordereddict/0.4.15/#files

ci: Revert to a simpler appveyor config

---

skbuild/resources/cmake/UseCython.cmake
tests/samples/cython-flags/CMakeLists.txt
tests/samples/cython-flags/hello/CMakeLists.txt
tests/samples/cython-flags/hello/__main__.py
tests/samples/cython-flags/hello/_hello.pyx
tests/samples/cython-flags/setup.py
tests/test_cython_flags.py

At the moment, CYTHON_FLAGS is read only once, when `include(UseCython)` is called. This means further changes to this variable from CMake code are not taken into account. This PR allows users to update CYTHON_FLAGS as needed (for instance when defining multiple modules with different flags).

Handle updates to CYTHON_FLAGS from CMake code

---

skbuild/setuptools_wrap.py

The example shows `src/hello`.
In my case I had hello at the toplevel of the project.
`package_dir={'': ''}` led to `prefix[-1]` being called, out of bounds,
fixed in this commit.
Note: I also tried `package_dir={'': '.'}` but the code blindly replaces all
dots with `/`, which led to `/MyPackage`.

skbuild: fix IndexError when prefix is empty

---

skbuild/constants.py
skbuild/setuptools_wrap.py

A first, partial fix for #529. This PR does two things: 1) it makes sure that `CMAKE_OSX_ARCHITECTURES` is not overridden if set externally, and 2) it makes sure that the correct wheel file name is given for `universal2` wheels (when `CMAKE_OSX_ARCHITECTURES` contains both `arm64` and `x86_64`).

Respect CMAKE_OSX_ARCHITECTURES and correctly produce universal2 macOS wheels

---

tests/test_cmaker.py

Fix the regular expression in test_get_python_version to permit
the minor version to contain more than one digit.  This fixes the test
on Python 3.10.

fix: fix regex in test_get_python_version for Python 3.10

---

.github/workflows/ci.yml

At this point, I think it's redundant with Azure. But we can keep it, no harm.

ci: include search vars in GHA too

---

skbuild/constants.py

Followup to #555. The format is `-arch <arch>`, which was in some version of the PR I think but didn't make into the final version. Using a simpler method than my original one, anyway. Testing in https://github.com/henryiii/scikit_build_example/pull/3 (which was actually supposed to target pybind/scikit_build_example, but this is fine for a test.

fix: archflags was not being parsed correctly

---

CHANGES.rst
setup.cfg
skbuild/cmaker.py
skbuild/platform_specifics/abstract.py
skbuild/platform_specifics/windows.py
tests/test_broken_project.py
tests/test_platform.py
tests/test_skbuild.py

This takes _just_ the non-2019 changes out of #526. Should make it easier to debug the issue with the failure there.
(pass through architecture, and test fixes)

fix: support and always call MSVC with -A

---

tests/test_setup.py

Ignore for a failure in a single test on Windows. I think this is a test-only issue on CI runners; I can't reproduce locally.
This test uses deprecated "setup_requires" instead of PEP 518 dependencies, anyway - it doesn't even look correct to me - you need to "install_requires" if you use setup_requires if you want to use it (then it sits around after the build, which is incorrect, etc).
See #566.

tests: ignore Ninja timing issue

---

README.rst

This commit removes the badge because the website https://landscape.io
is not responsive.

docs: Remove broken "Health" badge from README

---

requirements-docs.txt
requirements.txt

This commit is intended to remove false positive indicating that
requirements are outdated.
Fixes #573

chore: Add requires.io hints to requirements files

---

skbuild/platform_specifics/windows.py

Enable new Windows platform for CMakeVisualStudioIDEGenerator.
Tested with CMake Python distribution wheel generation on win-arm64.

Add ARM64 as a new Windows platform

---

skbuild/command/bdist_wheel.py

This fixes #596 by removing the custom logic that is lowering the macOS version incorrectly. This was originally there because Python defaults to whatever it was built with, and 10.6 was too low for modern macOS. However, all normal Pythons (everything except the dead 3.5) have 10.9 or better installers now, and this is causing the (correct) calculation of the version to be lost. Users should always set `MACOS_DEPLOYMENT_TARGET`, and most wheel building tools will do this for you just in case.
Draft until I'm sure it works or can add tests.

fix: avoid forcing the macOS version

---

skbuild/resources/cmake/FindPythonExtensions.cmake
skbuild/resources/cmake/UsePythonExtensions.cmake
skbuild/resources/cmake/targetLinkLibrariesWithDynamicLookup.cmake

This adds the option SKBUILD_LINK_LIBRARIES_KEYWORD which can be set to PRIVATE,
PUBLIC, or INTERFACE or left empty (the default) to use the old form of
target_link_libraries.
A similar change was done in FindCuda.cmake: https://gitlab.kitware.com/cmake/cmake/-/commit/9f41bfd7b9e6e8a7545f741f872949d2ae801978
This fixes https://github.com/scikit-build/scikit-build/issues/261
This still requires documentation and I have to test it.

Add option to use modern form of target_link_libraries

---

.github/workflows/ci.yml
noxfile.py
skbuild/platform_specifics/windows.py
tests/test_skbuild.py

Tested on Windows 11 (21H2) with Python 3.9.9 and Visual Studio Community 2022 (17.0.5).
<details><summary>Nox results</summary>
```
$Env:SKBUILD_TEST_FIND_VS2022_INSTALLATION_EXPECTED=1   
nox
nox > Running session lint
nox > Creating virtual environment (virtualenv) using python.exe in .nox\lint
nox > python -m pip install pre-commit
nox > pre-commit run -a
check for added large files..............................................Passed
check for case conflicts.................................................Passed
check for merge conflicts................................................Passed
check for broken symlinks............................(no files to check)Skipped
check yaml...............................................................Passed
debug statements …
```

feat: add VS2022 support on Windows

---

skbuild/cmaker.py

This patch considers the LIBDIR variable from both `distutils.sysconfig` and `sysconfig`. This is necessary to correctly detect the python library path when using pypy with recent setuputils versions.  (See #618.)

Improve detection of python library path

---

.github/workflows/ci.yml
noxfile.py
tests/test_cmaker.py
tests/test_issue284_build_ext_inplace.py
tests/test_skbuild.py

Adding PyPy. Two tests fail on macOS, but having the rest of the tests is better than not having them, and hopefully we can solve those issues eventually.

ci: test pypy

---

skbuild/cmaker.py
tests/test_cmaker.py

This improves on #624 reenabling the test for the python library which is found correctly now. I did not know how to fix the inplace build test, though.

Detect python library on macos + pypy

---

skbuild/cmaker.py

This fixes an issue in cmaker.py which doesn't detect the libpython shared lib because sysconfig.get_config_var('LIBDIR') already contains the multiarch subdir.

fix: detect python library on Focal Fossa

---

.github/workflows/ci.yml
.readthedocs.yml
MANIFEST.in
setup.cfg
setup.py

Pulling out the fixes from #634 and #631 that were unrelated and are easy to merge.
Two non-CI changes: There's now a `[docs]` extra (so the readthedocs is better), and an old warning about `[wheel]` being replaced by `[bdist_wheel]` has been fixed.
- ci: fix old if
- ci: fix PyPy not found on win/macOS
- ci: cancel in-progress on repeated pushes
- tests: Windows Nox doesn't find PyPy
- docs: add docs config file
- fix: warning produced about bdist_wheel

ci: assorted fixes

---

.github/workflows/ci.yml
requirements-dev.txt
setup.cfg
skbuild/cmaker.py
tests/conftest.py
tests/samples/hello-pep518/CMakeLists.txt
tests/samples/hello-pep518/MANIFEST
tests/samples/hello-pep518/README.md
tests/samples/hello-pep518/pyproject.toml
tests/samples/hello-pep518/setup.py
tests/samples/hello-pep518/src/hello/__init__.py
tests/samples/hello-pep518/src/hello/hello_py.cpp
tests/test_pep518.py

Fixes #628.
~~Builds on / requires #634; must be able to force the version in order to get the tests to pull the local scikit_build wheel.~~
About 95% of the work was in adding the test, the fix was pretty easy. :)

fix: pull ninja path if module available

---

.github/workflows/ci.yml

The extra job shouldn't be needed anymore, and was missing a Python 3.5 initialize anyway (since it's past EOL it's not installed by default in GHA runners anymore), causing it to be broken.
We also don't need to run on 3.9 for win & macOS, we already do 2.7 (macOS), 3.5, and 3.10.

ci: drop unneeded job

---

CHANGES.rst
docs/usage.rst
skbuild/cmaker.py
skbuild/setuptools_wrap.py
tests/samples/test-cmake-target/CMakeLists.txt
tests/samples/test-cmake-target/setup.py
tests/test_cmake_target.py
tests/test_cmaker.py

Parses the command line for the `--target` option.
And also provide the `cmake_install_target` parameter in `setup.py`
The command line argument has preference over the `cmake_install_target` from
`setup.py`.
This allows the user to point to targets other than 'install'.
The user has to set a target in CMake to install only a specific
component.
```cmake
install(TARGETS foo COMPONENT runtime)
add_custom_target(foo-install-runtime
${CMAKE_COMMAND}
-DCMAKE_INSTALL_COMPONENT=runtime
-P "${PROJECT_BINARY_DIR}/cmake_install.cmake")
```

Add cmake_target to change the target used by CMake

---

skbuild/command/generate_source_manifest.py
skbuild/command/sdist.py
skbuild/setuptools_wrap.py
tests/pytest_helpers.py
tests/samples/hello-cython/setup.py
tests/samples/test-include-exclude-data-with-base/MANIFEST.in
tests/samples/test-include-exclude-data/MANIFEST.in
tests/test_command_line.py
tests/test_hello_cython.py
tests/test_include_exclude_data.py
tests/test_issue401_sdist_with_symlinks.py
tests/test_manifest_in.py

Fixes https://github.com/scikit-build/scikit-build/issues/401.
Notes:
* Updated `generate_source_manifest.py` to produce a `MANIFEST.in` file instead of a `MANIFEST` file.

Use sdist command from setuptools instead of distutils

---

docs/usage.rst
skbuild/cmaker.py
skbuild/setuptools_wrap.py

Closes #588, would make supporting conda-forge easier, less workarounds like the ones in that issue and https://github.com/conda-forge/correctionlib-feedstock/blob/1d49847e4ac8e69967142146e8cbac81173ee3d3/recipe/setup.patch required.
If this looks like a good idea I can add tests and such.

feat: support CMAKE_ARGS

---

skbuild/cmaker.py

The library name in pypy 3.9 has changed. The '-c' moved to the end. This PR patches the candidate matrix to "make it work". It doesn't really fit nicely in the current matrix, though.

fix library dedection for pypy 3.9

---

skbuild/command/install_lib.py

`install_lib.run()` in [setuptools](../../../pypa/setuptools/blob/v60.9.3/setuptools/command/install_lib.py#L12) expects that the `outfiles` list is returned from `install_lib.install()`, otherwise byte-compilation is skipped.

fix: do byte-compilation in install_lib

---

skbuild/setuptools_wrap.py

Currently when scikit-build copies files from the source tree to the build tree (files that do not need to be compiled, e.g. pure Python files or Cython headers) it uses the `package_data` dict as a way to keep track of these files since data files are subject to the same requirements at this stage. `skbuild` assumes that modifying the `package_data` dict in place is safe [here](https://github.com/scikit-build/scikit-build/blob/master/skbuild%2Fsetuptools_wrap.py#L978) because it deep copies the `package_data` parameter passed to setup.py [here](https://github.com/scikit-build/scikit-build/blob/master/skbuild%2Fsetuptools_wrap.py#L513). However, deep copying is not sufficient in the scenario where the calling code constructs the input dict such that all values are actually references to …

Ensure that each package has a separate list of data elements.

---

CHANGES.rst
skbuild/cmaker.py
tests/conftest.py
tests/samples/hello-numpy/CMakeLists.txt
tests/samples/hello-numpy/MANIFEST
tests/samples/hello-numpy/README.md
tests/samples/hello-numpy/pyproject.toml
tests/samples/hello-numpy/setup.py
tests/samples/hello-numpy/src/hello/__init__.py
tests/samples/hello-numpy/src/hello/hello_py.cpp
tests/test_cmaker.py
tests/test_numpy.py

Closes #506 and closes #516 and closes #553.

Support FindPython.

---

docs/usage.rst
tests/samples/hello-numpy/pyproject.toml
tests/samples/hello-pep518/pyproject.toml

wheels is automatically installed by PEP 517 front ends, when building wheels. This was a documentation mistake in setuptools: https://github.com/pypa/setuptools/commit/f7d30a9529378cf69054b5176249e5457aaf640a

remove redundant `wheel` dependency

---

skbuild/exceptions.py
skbuild/setuptools_wrap.py

There does not seem to be a robust solution for editable installs (#370, #436, #546, #579, #697). The closest I've been able to get raises from `_classify_installed_files`, even though everything looks exactly as one might expect for an editable install. The only thing added here is a new exception class that gets raised in this situation so that the exception can be safely singled out and permitted, without catching every `SKBuildError`. Its not an ideal solution to the editable installation problem, but having more detailed exceptions sounds like an all-around plus.

Finer exceptions and hopes for editable installs.

---

docs/usage.rst

setup_requires is deprecated in setuptools and it is possible to achieve the same using an `in-tree backend`.

replace guide for setup_requires with in-tree backend

---

skbuild/resources/cmake/FindCython.cmake
skbuild/resources/cmake/UseCython.cmake

The language level of Cython depends on Cython version, not the host Python version. Avoiding this avoids requiring FindPythonLibs, which should stop breaking this when using FindPython.
Generalizing FindCython to use an existing discovery of Python and not trigger it's own.
CC @maxbachmann.

fix(Cython): support FindPython

---

.pre-commit-config.yaml
pyproject.toml
requirements.txt
skbuild/_version.pyi
skbuild/cmaker.py
skbuild/command/__init__.py
skbuild/command/build_ext.py
skbuild/command/build_py.py
skbuild/command/egg_info.py
skbuild/command/install.py
skbuild/command/install_lib.py
skbuild/command/install_scripts.py
skbuild/command/sdist.py
skbuild/constants.py
skbuild/platform_specifics/windows.py
skbuild/setuptools_wrap.py
skbuild/typing.py
skbuild/utils/__init__.py
tests/test_logging.py

This was sitting around, let's go ahead and see what the diff looks like. I was playing with monkeytype.
- chore: update mypy settings a bit
- chore: run monkeytype, update old workarounds
Looks like monkey type was too specific, some need generalization. :)
Edit: Worked on the added types, and got mypy running by default.
A few notes:
* There are several type ignores due to https://github.com/python/mypy/issues/12344
* I didn't work out all the details of Distribution, so there are lots of type ignores there
* There are a few minor cleanups noticed by mypy, like random trailing commas

chore: enable basic mypy

---

.github/actions/setup-nox/action.yml
CHANGES.rst
README.rst
setup.py

@jcfr, @thewtex, this has messaging about the future of Scikit-build, worth verifying it's reasonable before approving! I'd like to get this out fairly soon, as it seems to be needed for Python 3.11. There are other known bugs, but it's better to get some known fixes out (especially 3.11 support!) than wait for perfection.
Closes #777.

chore: prepare for 0.16

---

pyproject.toml

The distutils vendored in setuptools throws this error in a couple of tests:
```
[   37s] ______________________________ test_test_command _______________________________
[   37s] 
[   37s]     def test_test_command():
[   37s]         with push_dir():
[   37s]     
[   37s]             tmp_dir = _tmpdir("test_test_command")
[   37s]             project = "issue-274-support-one-package-without-package-dir"
[   37s]             prepare_project(project, tmp_dir)
[   37s]             initialize_git_repo_and_commit(tmp_dir, verbose=True)
[   37s]     
[   37s]             try:
[   37s] >               with execute_setup_py(tmp_dir, ["test"], disable_languages_test=True):
[   37s] 
[   37s] project    = 'issue-274-support-one-package-without-package-dir'
[   37s] tmp_dir    = …
```

Ignore distutils deprecation warning

---

.github/workflows/ci.yml
.gitignore
noxfile.py
pyproject.toml
requirements-dev.txt
skbuild/utils/__init__.py
tests/conftest.py
tests/test_distribution.py
tests/test_hello_cpp.py
tests/test_issue274_support_default_package_dir.py
tests/test_issue274_support_one_package_without_package_dir.py
tests/test_issue334_configure_cmakelists_non_cp1252_encoding.py
tests/test_setup.py

- tests: include printout of installed packages of interest
- tests: remove usage of raw "path"
- chore: ignore venv dirs
- fix: handle logging changes in setuptools 65.6+
- tests: mark some tests deprecated
- ci: pass job
This also ensures we are using the latest setuptools and wheel in the tests, which should help us see issues before (too many) users see them.

fix: handle logging changes in setuptools 65.6+

---

docs/usage.rst

This fixes the function signature of `get_requires_for_build_wheel` to be compliant with pep517 (see https://github.com/pypa/setuptools/pull/3730)

fix function signature of get_requires_for_build_wheel

---

skbuild/constants.py
skbuild/setuptools_wrap.py
tests/test_issue342_cmake_osx_args_in_setup.py

Should fix https://github.com/conda-forge/frictionqpotspringblock-feedstock/pull/51 hopefully. Hard to test without deploying it or applying this as a patch to the scikit-build feedstock.

fix: conda-forge uses -DCMAKE_SYSTEM_PROCESSOR, so respect that too

---

skbuild/resources/cmake/FindPythonExtensions.cmake
tests/samples/issue-668-symbol-visibility/CMakeLists.txt
tests/samples/issue-668-symbol-visibility/hello/__init__.py
tests/samples/issue-668-symbol-visibility/hello/_hello.cxx
tests/samples/issue-668-symbol-visibility/pyproject.toml
tests/samples/issue-668-symbol-visibility/setup.py
tests/test_issue668_symbol_visibility.py

This partially reverts f6ea5d0af (FindPythonExtensions: Set symbol visibility
to export only module init function) to ensure all local symbols are externally
visible.
This change is required to ensure library can resolve against
symbols other than the CPython module entrypoint (`PyInit_<moduleName>`
or `init<moduleName>`).
Since selectively listing additional symbols is not scalable (see [1]), this
commit ensures all symbols are visible.
[1] https://gcc.gnu.org/wiki/Visibility
Questions
* Is the issue fixed by this commit also a problem on windows ?
Additional required changes:

FindPythonExtensions: Do not override cpp symbols when using gcc on Linux

---

CHANGES.rst

Would like to release the recent change before moving ahead with modernization.

docs: prepare for 0.16.7

---

.pre-commit-config.yaml
pyproject.toml

Ruff now supports `force-to-top`.

chore: move isort to using Ruff

---

.pre-commit-config.yaml
docs/usage.rst
pyproject.toml
skbuild/_compat/tomllib.py
skbuild/setuptools_wrap.py

This PR attempts to match the default behavior of `include_package_data` in setuptools, which is somewhat subtle in that the default is dependent on the existence of certain tables in pyproject.toml.
Resolves #864.

Match setuptools behavior for include_package_data default.

---

skbuild/cmaker.py
skbuild/setuptools_wrap.py

Resolves #721. I did not bother to add testing since this is just a helping the user understand an invalid edge case (and given the overall thrust towards scikit-build-core migration anyway).

Provide more useful error if user provides CMAKE_INSTALL_PREFIX

---

pyproject.toml
skbuild/setuptools_wrap.py

Was targeting #749, but that will be a followup now. This just changes parameter handling so that input parameters are no longer mutated. (yuck)

refactor: avoid mutating function input parameters

---

skbuild/cmaker.py

On Windows the name of the PyPy import library is pythonXY.lib. For some reason (Linux?) existing code overwrote 'python' stem guess with ["pypy-c", "pypy3-c", "pypy"] instead of appending.
Testing: existing tests **already cover this** in `tests/test_cmaker.py::test_get_python_library`. However PyPy tests aren't run on Windows on Github, only on Linux. I assume this is why this issue wasn't detected by tests.
To test "install" PyPy (e.g. unpack it) on Windows in folder of your choice and then do
```cmd
nox -s tests --force-python c:\<path_where_you_unpacked_pypy>\python3.exe -- -k test_get_python_library
```
resolves #701

fix: detect PyPy library correctly on Windows (#701)

---

skbuild/platform_specifics/windows.py

The code that creates the `default_generators` for Visual Studio generators was using the host architecture instead of the target architecture when cross-compiling so finding the compiler would fail.
This reuses the existing helper function to get the architecture for the candidate generators.

Fix cross-compiling Windows ARM64

---

CHANGES.rst
skbuild/constants.py

If possible, an empty variable should behave like an unset one. This might help with #911, depending on what caused that.

fix: empty MACOSX variable should be treated as unset

---

pyproject.toml
tests/samples/test-include-exclude-data-with-base/setup.py
tests/samples/test-include-exclude-data/setup.py

Removes one warning (seen in our tests & #753), previously just ignored.

tests: update for setuptools explicit package listing requirement

---

.github/workflows/ci.yml
noxfile.py
pyproject.toml

Codecov package has been [removed](https://github.com/codecov/codecov-python), use github action instead. Please fix the CI as needed.
- There are no coverage for `main` because the default branch changed :shrug:
- Should the tests be tagged according to the os and python version?

fix: codecov ci

---

skbuild/setuptools_wrap.py

This was fixed upstream, but we can just pass this down and only fail if CMake fails. Closes #911.

fix: make empty CMAKE_OSX_DEPLOYMENT_TARGET a warning

---

skbuild/cmaker.py
tests/test_cmaker.py
tests/test_command_line.py

There will always be unused vars, so we could just hide them all. CMAKE_PREFIX_DIRS, in scikit-build-core, is causing this used variable message, and is hard to integrate with the config init method we use there, so experimenting with just removing all of them. Though, there, I do see a mention of "FORCE" in the docs for `-C`, so that's encouraging!

fix: remove unused var warning

---

skbuild/cmaker.py

In CMaker._guess_python_library(), there is a path where python_library can be set to a file name without a path. For example, this happens when using a venv in a MinGW envronment on Windows. This gets passed to CMake via Python_LIBRARY which causes CMake to fail.
To fix it, we validate that the path exists on disk before returning the value or return None if it does not exist.

fix: validate value before returning library path

---

skbuild/cmaker.py

Pretty sure this is needed also given https://github.com/scikit-build/scikit-build-core/issues/283. Ideally this needs to be fixed upstream.

fix: only add Python_LIBRARY on Windows

---

skbuild/cmaker.py
skbuild/constants.py

fix: only add Python_LIBRARY on Windows MSVC

---

skbuild/cmaker.py
skbuild/platform_specifics/abstract.py

Notice this in #945, we can clean this up a bit.
(Not sure what is happening there, but at least the error message can be simpler).

fix: slightly nicer traceback for failed compiler

---

skbuild/cmaker.py

Suggested improvement for openCV. I think this should go back to returning None in 0.18, but this would help the perceived regression for OpenCV in 0.17.2. See #940.

revert: keep return type string if python lib non-existing for now

---

skbuild/resources/cmake/FindPythonExtensions.cmake

Fixing one warning that can show up, mentioned in #959, simi-followup to #940.

fix: avoid 'not found' warning if libs are not found

---

skbuild/resources/cmake/FindPythonExtensions.cmake

This reverts commit 8ee16a00986bad2d989fb64d786f949097479a6a.
This was to hide the warning, but `PYTHON_INCLUDE_DIRS` was not getting set from `PYTHON_INCLUDE_DIR`, and it caused breakages when used outside of SKBUILD. Fixes #963.

Revert "fix: avoid 'not found' warning if libs are not found (#960)"

---

CHANGES.rst
noxfile.py
skbuild/resources/cmake/FindPythonExtensions.cmake

Adding a way to test downstream projects too.
Closes #957. Added a way to manually test a downstream package. The following work after this change:
```
docker run --rm -v $PWD:/sk -w /sk -t quay.io/pypa/manylinux2014_x86_64:latest pipx run --system-site-packages nox -s downstream -- https://github.com/Blosc/python-blosc2
docker run --rm -v $PWD:/sk -w /sk -t quay.io/pypa/manylinux2014_x86_64:latest pipx run --system-site-packages nox -s downstream -- https://github.com/glotzerlab/freud
```

fix: make sure include dir is found

---

skbuild/cmaker.py

Fix last part of https://github.com/scikit-build/scikit-build/issues/755 - generator args were not propagated.

fix: generator args were missing for actual compile

---

tests/test_issue668_symbol_visibility.py

Wrong line could be matched by mistake, e.g.
45: 0000000000010160     0 NOTYPE  LOCAL  DEFAULT   10 0000001a.plt_call.get_map

tests: fix match for get_map symbol

---

.gitignore
CHANGES.rst
noxfile.py

Main feature is 3.12.0b1 classifier, but also some new supported platforms.
- chore: nox nicer downstream
- chore: pyenv in gitignore
- docs: add changelog for 0.17.6

docs: prepare for 0.17.6

---

.distro/plans/main.fmf.dist-git
.distro/python-scikit-build.spec

- Added some changes from downstream
- Fixed CI failures from downstream (tmt tests were not detected properly because it uses an undocumented automatic tmt test detection)

fix: Fedora downstream CI

---

tests/test_hello_cython.py
tests/test_hello_fortran.py
tests/test_hello_pure.py
tests/test_manifest_in.py

setuptools 69.3.0 now canonicalizes package names in filenames, which means all dashes are now converted to underscores, leading to test failures due to FileNotFoundErrors. Handle both cases to support older and newer setuptools.

Support setuptools 69.3.0 changes in two tests

---

skbuild/setuptools_wrap.py

The user might not have permissions to change permissions on the executables. Aborting in that case seems premature, since the permissions might be sufficient after all.
Seen on nixpkgs, where the cmake execcutable is immutable.
```pytb
cffsubr> Traceback (most recent call last):
cffsubr>   File "/build/cffsubr-0.3.0/external/afdko/setup.py", line 222, in <module>
cffsubr>     main()
cffsubr>   File "/build/cffsubr-0.3.0/external/afdko/setup.py", line 172, in main
cffsubr>     setup(name="afdko",
cffsubr>   File "/nix/store/dg9b2drwhvdfxp9gmpyiav1isl6hji9d-python3.11-scikit-build-0.17.6/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 636, in setup
cffsubr>     os.chmod(executable, permissions)
cffsubr> PermissionError: [Errno 1] Operation not permitted: …
```

fix: Don't die on PermissionError during chmod

---

skbuild/resources/cmake/FindNumPy.cmake
skbuild/resources/cmake/FindPythonExtensions.cmake

I didn't have a chance to go through the whole repo, but I made this PR upstream to `zfpy` which vendors some files
https://github.com/LLNL/zfp/pull/217
If you want to monitor if this "works", please check build logs in https://github.com/conda-forge/zfpy-feedstock/pull/35
goodluck modernizing this.
There seems to be only a finite number of occurrences of distutils 
```
grep "(from|import) distutils" . -RE
```

Remove usage of deprecated distutils in cmake files

---

skbuild/platform_specifics/windows.py

If multiple locations are returned next line check is failing since there is no folder that is a concatenation of two paths. That results in multiple installs for the same VS version treated as there is no one installed.

Use first available option for vswhere output

---

.github/workflows/ci.yml
noxfile.py
pyproject.toml
skbuild/cmaker.py
tests/conftest.py

Adding 3.13.
Windows 3.13 is producing `LINK : fatal error LNK1104: cannot open file 'python313.lib' [C:\Users\runneradmin\AppData\Local\Temp\pytest-of-runneradmin\pytest-340\test_build0\_skbuild\win-amd64-3.13\cmake-build\_hello.vcxproj]`.

fix: support CPython 3.13 with windows lib finding fix

---

skbuild/constants.py
skbuild/platform_specifics/unix.py
skbuild/platform_specifics/windows.py
skbuild/resources/cmake/targetLinkLibrariesWithDynamicLookup.cmake
tests/samples/issue-668-symbol-visibility/CMakeLists.txt
tests/samples/test-filter-manifest/CMakeLists.txt

Fix https://github.com/scikit-build/scikit-build/issues/1066 by requiring CMake 3.5+. This was already done in some areas to stop warnings, but this applies it to the search for `cmake` vs. `cmake3`, with `cmake` now preferred, but cmake < 3.5 is ignored. This is more inline with scikit-build-core, which required 3.15+ and makes this user selectable.

fix: cmake 3.5+ requirement

---

pyproject.toml
skbuild/platform_specifics/platform_factory.py

This modification enables the execution of scikit-build within a Python crossenv environment, catering to both iOS and Android platforms.

iOS and Android support

---

tests/samples/issue-274-support-default-package-dir/setup.py
tests/samples/issue-274-support-one-package-without-package-dir/setup.py
tests/samples/issue-335-support-cmake-source-dir/wrapping/python/setup.py
tests/samples/test-filter-manifest/wrapping/python/setup.py

setuptools 72 and above now raise warnings for test_suite and tests_require directives in setup.py as support for setup.py test is preparing to be removed. These directives have been deprecated for quite some time, so just remove them from the sample setup.py files.

test: remove test directives

---

skbuild/cmaker.py
skbuild/setuptools_wrap.py

* Fix a bug where `CMAKE_ARGS` was not parsed with `shlex.split`, which was breaking with e.g. `CMAKE_ARGS` set to `-G "Unix Makefiles"`.
* Remove redundant `list(filter(None, ...))`
I wish I could just pass the CMake arguments as command line arguments. Apparently calling `setup.py` is the only way to do so, but deprecated (?). What's left is patching toml files (not great), or setting this env variable (ugly).

`setuptools_wrap.py`: parse `CMAKE_ARGS` with `shlex.split` like elsewhere

---

CONTRIBUTING.rst
azure-pipelines.yml
docs/generators.rst
docs/usage.rst
noxfile.py
pyproject.toml
skbuild/__init__.py
skbuild/_compat/typing.py
skbuild/cmaker.py
skbuild/platform_specifics/windows.py
tests/conftest.py
tests/pytest_helpers.py
tests/samples/issue-668-symbol-visibility/setup.py
tests/samples/issue-707-nested-packages/setup.py

We've had to disable most of our Python 3.7 tests in CI, so let's go ahead and drop it.

feat: drop Python 3.7
