- skbuild/cmaker.py
- skbuild/platform_specifics/abstract.py
- skbuild/platform_specifics/windows.py
- tests/test_skbuild.py
> update visual studio version mappings in windows platform

- tests/samples/cmake-files/FindPythonExtensions.cmake
- tests/samples/cmake-files/targetLinkLibrariesWithDynamicLookup.cmake
- tests/samples/tower-of-babel/CMakeLists.txt
- tests/samples/tower-of-babel/scripts/CMakeLists.txt
- tests/test_tower_of_babel.py
> [REBASED] weak linking module

- README.rst
Improving top level docs.
It will be nice to have the package badges working after the first pre-release tag ;-).
> Improve docs

- skbuild/cmaker.py
- tests/samples/fail-outside-project-root/setup.py
- tests/samples/fail-unless-skbuild-set/CMakeLists.txt
- tests/samples/fail-unless-skbuild-set/setup.py
- tests/samples/hello-cython/setup.py
- tests/samples/hello/setup.py
- tests/samples/pen2-cython/setup.py
- tests/samples/tower-of-babel/setup.py
- tests/test_skbuild_variable.py
> [REBASED] add CMake variable to project builds: "SKBUILD"

- skbuild/setuptools_wrap.py
- tests/__init__.py
- tests/test_hello.py
- tests/test_hello_cython.py
Hack adapted from https://github.com/espdev/ITKPythonInstaller
> setuptools_wrap: Force binary wheel generation. Fixes #106

- tests/test_cmaker.py
> test_cmaker: Add test for get_python_version and get_python_library.

- skbuild/cmaker.py
- skbuild/setuptools_wrap.py
- tests/__init__.py
- tests/test_hello.py
- tests/test_hello_cython.py
- tests/test_utils.py
This set of changes is done anticipating the introduction of `skbuild.setup` keywords like `cmake_source_dir` and `cmake_install_dir` useful to address  #165
> Refactor code

- CONTRIBUTING.rst
- docs/conf.py
- docs/index.rst
- docs/installation.rst
- docs/make_a_release.rst
- docs/readme.rst
- docs/usage.rst
Rendered documentation of proposed changes:
https://test-skb.readthedocs.io/en/doc-refresh/index.html
Proposed changes:
- `conf.py`
* Added check whether building locally or on rtd
* Comment out _static since unused and generated a build warning
- `index.rst`
* Migrated information from README to this document
* Added captions that provide sidebar captions
- `installation.rst` - edit titles and contents to improve readability
- `usage.rst` - edit content and code example to improve reader understanding 
- `make_a_release.rst` - Add doc to a "Maintainer" section of the docs
- `CONTRIBUTING.rst` - Edits for readability
Nice meeting you at PyData Carolinas too.
> Refresh docs

- skbuild/setuptools_wrap.py
This will allow to run command like "register" without having to
wait for CMake to complete.
> skbuild: Whilelist command expecting CMake to run. See #207

- CHANGES.rst
- docs/extension_build_system.rst
- docs/generators.rst
- docs/index.rst
- docs/usage.rst
- requirements-dev.txt
- skbuild/cmaker.py
- skbuild/platform_specifics/__init__.py
- skbuild/platform_specifics/abstract.py
- skbuild/platform_specifics/unix.py
- skbuild/platform_specifics/windows.py
- skbuild/setuptools_wrap.py
- tests/__init__.py
- tests/samples/fail-outside-project-root/other_project/CMakeLists.txt
- tests/test_broken_project.py
- tests/test_hello.py
- tests/test_skbuild.py
This topic is still **WORK IN PROGRESS**, the intent of this PR it to validate the work done so far.
> Fallback to use ms compiler for python27

- CHANGES.rst
> CHANGE: Add entry documenting fix for #265

- docs/generators.rst
- skbuild/cmaker.py
- skbuild/command/bdist_wheel.py
- skbuild/setuptools_wrap.py
- tests/test_cmaker.py
> setuptools_wrap: Add support for plat-name on macosx

- CHANGES.rst
- skbuild/cmaker.py
- skbuild/setuptools_wrap.py
- tests/__init__.py
- tests/test_hello_cpp.py
Suggested-by: woodring.jon@gmail.com
> setuptools_wrap: Improve --skip-cmake support

- CHANGES.rst
- skbuild/command/bdist_wheel.py
- tests/test_hello_cpp.py
> skbuild.command.bdist_wheel: Set "skbuild <version>" as wheel generator

- CHANGES.rst
- skbuild/command/build_py.py
- skbuild/command/install_lib.py
- skbuild/command/install_scripts.py
- skbuild/setuptools_wrap.py
- skbuild/utils/__init__.py
- tests/samples/test-include-exclude-data-with-base/CMakeLists.txt
- tests/samples/test-include-exclude-data-with-base/MANIFEST.in
- tests/samples/test-include-exclude-data-with-base/setup.py
- tests/samples/test-include-exclude-data-with-base/src/hello/data/subdata/hello_data1_include_from_manifest.txt
- tests/samples/test-include-exclude-data-with-base/src/hello2/data2/subdata2/hello2_data1_include_from_manifest.txt
- tests/samples/test-include-exclude-data/CMakeLists.txt
- tests/samples/test-include-exclude-data/MANIFEST.in
- tests/samples/test-include-exclude-data/hello/data/subdata/hello_data1_include_from_manifest.txt
- tests/samples/test-include-exclude-data/hello2/data2/subdata2/hello2_data1_include_from_manifest.txt
- tests/samples/test-include-exclude-data/setup.py
- tests/test_include_exclude_data.py
- tests/test_setup.py
> Add support for include_package_data/exclude_package_data

- CHANGES.rst
- docs/usage.rst
- skbuild/cmaker.py
- skbuild/platform_specifics/abstract.py
- skbuild/setuptools_wrap.py
- tests/__init__.py
- tests/test_setup.py
> setuptools_wrap: Install cmake first if found in  "setup_requires"

- CHANGES.rst
- pytest.ini
- skbuild/cmaker.py
- tests/samples/issue-334-configure-cmakelist-non-cp1252-encoding/CMakeLists.txt
- tests/samples/issue-334-configure-cmakelist-non-cp1252-encoding/setup.py
- tests/test_issue334_configure_cmakelists_non_cp1252_encoding.py
> test: Configure a project with CMakeLists.txt having UTF-8 characters

- CHANGES.rst
- skbuild/setuptools_wrap.py
- tests/test_issue342_cmake_osx_args_in_setup.py
> setuptools_wrap: Consider CMAKE_OSX_* set using cmake_args keyword

- docs/generators.rst
- docs/usage.rst
> doc: Add advanced usage section "Enabling parallel build"

- CHANGES.rst
- docs/usage.rst
- skbuild/cmaker.py
- skbuild/platform_specifics/abstract.py
- skbuild/setuptools_wrap.py
> Add support for "--skip-generator-test" option

- CHANGES.rst
- skbuild/resources/cmake/FindPythonExtensions.cmake
This incorporates my previous pull request #366, and adds an additional change to resolve issue #375 .
> Fixes for bugs with version-script.map

- scikit-ci.yml
See https://github.com/scikit-build/scikit-build/issues/409
> scikit-ci: Ensure codecov submission is skipped on azure-pipelines for GitHub PR

- CHANGES.rst
- skbuild/cmaker.py
- tests/test_cmaker.py
- tests/test_constants.py
> CMaker.check_for_bad_installs: Fix unclosed file resource

- CHANGES.rst
- azure-pipelines.yml
- skbuild/cmaker.py
- tests/test_cmaker.py
Let's see if this works.
Since PyPy is still in a catch-up mode where it releases every 3-6 months, I preferred to `wget` the latest release.
Follow on from #407, will fail until that is merged
> Add support for PyPy and setup continuous integration

- CHANGES.rst
- skbuild/cmaker.py
Co-authored-by: Isuru Fernando <isuruf@gmail.com>
> cmaker: Remove obsolete comments [ci skip]

- README.rst
- docs/index.rst
> Add link to scikit-build-sample-projects in README

- CHANGES.rst
- docs/cmake-modules/F2PY.rst
- skbuild/resources/cmake/FindF2PY.cmake
- skbuild/resources/cmake/UseF2PY.cmake
Update: this function in only handling pyf files, otherwise, it becomes too complex.
This PR supersedes https://github.com/scikit-build/scikit-build/pull/281 originally submitted by `@xoviat`
> Add UseF2PY

- skbuild/setuptools_wrap.py
> cmake process manifest callable

- CHANGES.rst
- azure-pipelines.yml
> ci: Disable broken Linux_PyPy3 testing on azure-pipelines

- CHANGES.rst
- tests/test_setup.py
Should fix CI failures seen in #493 and #495.
> Fix error with flake8 >= 3.8.x

- CHANGES.rst
- docs/generators.rst
Propose to link to latest version of cmake documentation rather than a specific version
> Proposal: Link to latest cmake documentation

- skbuild/constants.py
This improves the support for Apple Silicon by respecting the setting of ARCHFLAGS, just like setuptools does. Also fixed the output of names like "11.4" for the macOS version; for versions 11+, only the major version is used, and the minor version should remain 0. (Apple is now incrementing the major version every release, instead of the minor version, which is no longer stuck at 10).
Followup to #530.
> feat: better Apple Silicon support

- skbuild/constants.py
Follow up to comments on https://github.com/scikit-build/scikit-build/pull/556.
> refactor: pull out macos arch

- .gitignore
- noxfile.py
Pulling out the nox changes from #526 while that one is being debugged.
> chore: nicer nox for Windows dev

- skbuild/platform_specifics/abstract.py
Fixes a warning that shows up in the logs. There are more, but this is an easy one. :)
> fix: reduce a warning

- CHANGES.rst
- README.rst
- docs/make_a_release.rst
Updating the release procedure.
> docs: update release procedure

- .pre-commit-config.yaml
- CHANGES.rst
- CONTRIBUTING.rst
- README.rst
- docs/generators.rst
- docs/index.rst
- docs/make_a_release.rst
- docs/notes.rst
- docs/usage.rst
- skbuild/cmaker.py
Catching a few minor issues in the docs, like markdown syntax being used instead of rst in rst files.
> chore: add pygrep

- docs/usage.rst
See #591 - this mentions the current restriction on setup.cfg.
> docs: mention restriction on setup.cfg options

- skbuild/constants.py
> fix: conda cross-compile issue fix

- skbuild/utils/__init__.py
> fix: no error on broken logger

- .github/workflows/ci.yml
- noxfile.py
Using a nicer workaround for https://github.com/theacodes/nox/issues/340 than what we used before.
> tests: clean up nox workaround

- setup.cfg
- tests/samples/test-cmake-target/setup.py
- tests/test_cmaker.py
- tests/test_setup.py
Minor issue in #477.
- chore: issue cleared up
- fix: cmake_install_target in test
> tests: fix warning and error

- .pre-commit-config.yaml
- docs/generators.rst
- docs/usage.rst
Fixing a few smartquotes that leaked in.
> style: ban smartquotes

- .git-blame-ignore-revs
- CHANGES.rst
> docs: bump changelog

- .github/actions/setup-nox/action.yml
- .github/workflows/ci.yml
- noxfile.py
I'm not sure https://github.com/excitedleigh/setup-nox/issues/419 is going to be fixed, so this adds our own action for it.
> ci: custom nox action

- .github/workflows/ci.yml
- CHANGES.rst
- skbuild/cmaker.py
Fixes #694.
- ci: drop macOS PyPy becuase it is too slow
- fix: typo breaking SKBUILD_CONFIGURE_OPTIONS
- docs: update changelog
> fix: correcting typo

- .github/workflows/ci.yml
- CHANGES.rst
- skbuild/platform_specifics/cygwin.py
- skbuild/platform_specifics/platform_factory.py
- skbuild/platform_specifics/windows.py
- tests/test_numpy.py
- tests/test_pep518.py
- tests/test_platform.py
- tests/test_setup.py
- tests/test_utils.py
Add detection for cygwin.
Close #484
> Cygwin Platform Detection

- .github/workflows/ci.yml
- CHANGES.rst
Preparing for the final (I mean it this time!) Python 2 release. At least I think I mean it.
> chore: update changelog

- azure-pipelines.yml
I'm rather expecting to fail due to the setuptools 64 release, which I believe breaks us.
> ci: update azure

- setup.py
- skbuild/platform_specifics/README.rst
- skbuild/platform_specifics/__init__.py
`include_platform_data` can cause issues.
> fix: be specific about platform data

- .pre-commit-config.yaml
- skbuild/setuptools_wrap.py
* Removed redundant list() ctor call and added a flake8-plugin to catch these issues in the future.
* Also re-synchronized black version with blacken-docs.
> chore: Apply flake8-comprehensions

- skbuild/cmaker.py
- tests/test_cmaker.py
See #743. Makes this a tiny bit easier to use for PyPy.
> fix(pypy): include find impl setting

- .github/dependabot.yml
Should help with keeping actions up to date.
> feat: add dependabot for GHA

- skbuild/cmaker.py
A bit of cleanup, and this might be a bit more likely to work - the MODULE path wasn't absolute before. Investigating a missing module failure.
> chore: simply strings a bit

- skbuild/cmaker.py
- skbuild/command/__init__.py
- skbuild/platform_specifics/linux.py
- skbuild/setuptools_wrap.py
Thanks to @dosisod for the pathlib usage here, from https://github.com/dosisod/refurb/issues/14.
> chore: cleanup some syntax with refurb suggestions

- pyproject.toml
- skbuild/__init__.py
- skbuild/command/bdist.py
- skbuild/command/bdist_wheel.py
- skbuild/command/build.py
- skbuild/command/build_ext.py
- skbuild/command/build_py.py
- skbuild/command/clean.py
- skbuild/command/egg_info.py
- skbuild/command/generate_source_manifest.py
- skbuild/command/install_lib.py
- skbuild/command/sdist.py
- skbuild/command/test.py
- skbuild/platform_specifics/abstract.py
- skbuild/platform_specifics/cygwin.py
- skbuild/platform_specifics/linux.py
- skbuild/platform_specifics/osx.py
- skbuild/platform_specifics/platform_factory.py
- skbuild/platform_specifics/unix.py
- skbuild/platform_specifics/windows.py
- skbuild/setuptools_wrap.py
- skbuild/utils/__init__.py
Simpler imports based on what's actually there.
> fix: add mypy strict-mode checking

- skbuild/cmaker.py
- tests/test_cmaker.py
This might help in cases where this errors out. If there are cases where it doesn't find correctly, then we'll need to fix & backport.
> fix: try using a different mechanism for FindPython

- skbuild/setuptools_wrap.py
This should type better and is simpler.
> refactor: use kw arguments for sk args in setup

- skbuild/cmaker.py
- skbuild/command/bdist_wheel.py
- skbuild/command/egg_info.py
- skbuild/platform_specifics/abstract.py
- skbuild/platform_specifics/windows.py
- skbuild/setuptools_wrap.py
- skbuild/utils/__init__.py
This should help a bit with scrambled output.
> fix: better buffering and output streams

- setup.py
> fix: dist issues

- skbuild/cmaker.py
- tests/test_cmaker.py
Issue on conda-forge after #774. This gets it working again, and PyPy is working too (along with a workaround).
> fix: conda issue with discovery in 0.16

- pyproject.toml
> tests: change warning filtering

- skbuild/cmaker.py
- skbuild/platform_specifics/abstract.py
- skbuild/platform_specifics/windows.py
- tests/test_skbuild.py
Starting by checking to see if this function works.
> fix: adjustmetns for native ARM support for Windows

- skbuild/cmaker.py
Should help get cross-compiles working.
> fix: Windows ARM cross-compile

- docs/usage.rst
Use the Hello example as the example of Basic Usage. It might be helpful for Python user who have limited C++ experience.
> Make Basic Usage tutorial more detail.

- pyproject.toml
- tests/conftest.py
- tests/test_include_exclude_data.py
- tests/test_issue401_sdist_with_symlinks.py
- tests/test_manifest_in.py
- tests/test_numpy.py
- tests/test_pep518.py
- tests: add marker for nosetuptoolsscm
- tests: add isolated marker
See #791.
> tests: add markers for isolated & nosetuptoolsscm

- skbuild/constants.py
- skbuild/setuptools_wrap.py
> fix: cmake path pulled from cmake module if possible

- skbuild/cmaker.py
- skbuild/command/generate_source_manifest.py
- skbuild/platform_specifics/abstract.py
- skbuild/platform_specifics/windows.py
- tests/__init__.py
- tests/conftest.py
- tests/test_broken_project.py
- tests/test_numpy.py
- tests/test_pep518.py
> refactor: use subprocess.run

- skbuild/constants.py
- skbuild/setuptools_wrap.py
> fix: cmake import should only be used if valid

- CHANGES.rst
- tests/test_distribution.py
- fix(tests): generator does not have a len
- docs: update changelog for 0.16.6
> fix(tests): generator does not have a len

- .pre-commit-config.yaml
- skbuild/cmaker.py
- skbuild/command/generate_source_manifest.py
- skbuild/setuptools_wrap.py
- tests/__init__.py
- tests/test_broken_project.py
- tests/test_cmaker.py
- tests/test_command_line.py
- tests/test_hello_cpp.py
- tests/test_issue274_support_default_package_dir.py
- tests/test_issue274_support_one_package_without_package_dir.py
- tests/test_issue342_cmake_osx_args_in_setup.py
- tests/test_issue352_isolated_environment_support.py
- tests/test_issue401_sdist_with_symlinks.py
- tests/test_outside_project_root.py
- tests/test_platform.py
- tests/test_setup.py
- tests/test_skbuild.py
Yearly style adjustment from Black.
> chore: update to black 23

- pyproject.toml
- tests/samples/issue-668-symbol-visibility/hello/__init__.py
> chore: activate isort in Ruff

- .pre-commit-config.yaml
- pyproject.toml
> tests: hide another warning

- .pre-commit-config.yaml
- skbuild/command/build_ext.py
- skbuild/command/egg_info.py
- skbuild/command/sdist.py
- skbuild/setuptools_wrap.py
- skbuild/utils/__init__.py
Based on update to setuptools in typeshed.
> chore: fix some setuptools types

- skbuild/resources/cmake/FindF2PY.cmake
- skbuild/resources/cmake/FindPythonExtensions.cmake
- skbuild/resources/cmake/UseF2PY.cmake
- skbuild/resources/cmake/UsePythonExtensions.cmake
> Misc. fixes for F2PY and PythonExtensions modules

- skbuild/resources/cmake/FindF2PY.cmake
See https://github.com/orgs/scikit-build/discussions/821#discussioncomment-5196590.
> fix: use f2py get_include if present

- pyproject.toml
- skbuild/cmaker.py
- skbuild/setuptools_wrap.py
- tests/__init__.py
- tests/test_setup.py
Makes the error tracebacks a little cleaner.
> style: enable errmsg code

- tests/pytest_helpers.py
Makes the error messages a little smarter.
> tests: set comparison

- skbuild/setuptools_wrap.py
This fixes #749, followup to #899. This is just a simple fix to only inject this if it's not specified, and to read the correct version for `--config`.
> fix: allow build type overriding

- .gitignore
- .pre-commit-config.yaml
- pyproject.toml
> chore: add sdist check & fix

- .github/workflows/ci.yml
- tests/pytest_helpers.py
- tests/test_issue284_build_ext_inplace.py
> ci: add PyPy Win & macOS

- skbuild/platform_specifics/windows.py
See https://github.com/charliermarsh/ruff/pull/3876.
> style: all-caps win envvar

- skbuild/resources/cmake/targetLinkLibrariesWithDynamicLookup.cmake
This pull-request fixes dynamic linking when cross-compiling on macOS.
It revisits the approach used to support cross-compilation when no emulator is available.
This is done by further improving on fixes integrated through https://github.com/scikit-build/scikit-build/commit/c0ec848644a22fb165018be7882b24099dcec2ae (`Fix targetLinkLibrariesWithDynamicLookup`) and https://github.com/scikit-build/scikit-build/commit/07b2c4ff0b03f830456eb1c17bae87437d5bf5c5 (`fix: assume success for osx_dynamic_lookup when cross compiling`)
Messages reported during configuration are also improved, when the compile tests are assumed to pass when cross-compiling without emulator, a clear message is reported.
For example:
```
Performing Test Weak Link MODULE -> SHARED (osx_dynamic_lookup) - Assuming Success …
```
> targetLinkLibrariesWithDynamicLookup: Fix support for cross-compilation exception

- skbuild/cmaker.py
- tests/test_cmaker.py
Attempting to fix #912; I though this had a problem before, but let's try it.
> fix: include library for FindPython

- .github/workflows/ci.yml
- CHANGES.rst
> docs: update changelog for 0.17.0

- docs/changes.rst
- docs/index.rst
- docs/skbuild.command.rst
- docs/skbuild.platform_specifics.rst
- docs/skbuild.rst
- docs/skbuild.utils.rst
- docs/usage.rst
- noxfile.py
Changelog was listed twice. Add a nox session to update the API docs. Mention scikit-build-core in a couple of places. Warn about passing variable via command line.
> docs: fix duplication and update some text

- .github/workflows/ci.yml
- CHANGES.rst
- noxfile.py
- pyproject.toml
- tests/conftest.py
- tests/test_numpy.py
Setuptools injecting distutils is enough to keep this working.
> ci: add Python 3.12 alpha 7+

- skbuild/cmaker.py
Seen in https://github.com/maxbachmann/Levenshtein/issues/52.
> fix: old CMake breaks when lib specified

- .distro/scikit-build.spec
- .packit.yaml
Equivalent implementation with scikit-build-core. Probably will have to install the app here too
> ci: Add fedora packaging with packit automation

- .coveragerc
- .github/codecov.yml
- .github/workflows/ci.yml
- noxfile.py
- pyproject.toml
Also adding durations to our slowest job.
> chore: update some coverage settings

- CHANGES.rst
Small update mostly to fix the regression for CMake < 3.24 + FindPython.
> chore: update to 0.17.1

- CHANGES.rst
Preparing for a small 0.17.2 release.
> docs: prepare for 0.17.2

- CHANGES.rst
- docs: prepare changelog for 0.17.3
> docs: prepare for 0.17.3

- CHANGES.rst
Very small release to fix a possible issue.
> chore: prepare for 0.17.4

- skbuild/platform_specifics/platform_factory.py
> fix: add support for netbsd & pyodide (future)

- CHANGES.rst
Small release but the Ninja fix is pretty important, IMO.
> docs: prepare changelog for 0.17.5

- skbuild/platform_specifics/platform_factory.py
- skbuild/platform_specifics/sunos.py
- skbuild/resources/cmake/FindPythonExtensions.cmake
- tests/test_platform.py
> fix: add support for sunos

- pyproject.toml
> docs: fix link to changelog

- .distro/plans/rpmlint.fmf
- .distro/tests/rpmlint.fmf
Hotfix for https://github.com/scikit-build/scikit-build-core/issues/307#issuecomment-1553599210
> fix: rpm inspect test failures

- pyproject.toml
- skbuild/cmaker.py
- skbuild/command/__init__.py
- skbuild/platform_specifics/cygwin.py
- skbuild/platform_specifics/windows.py
- skbuild/setuptools_wrap.py
- skbuild/utils/__init__.py
> chore: clean up pylint

- .github/workflows/ci.yml
This reverts commit 210cc9df056f4d43b008e00ec5a4d691861b2d4c.
> Revert "chore(deps): bump codecov/codecov-action from 3 to 4 (#1027)"

- .pre-commit-config.yaml
- pyproject.toml
- tests/test_issue342_cmake_osx_args_in_setup.py
- tests/test_setup.py
See https://github.com/scientific-python/cookie/pull/299.
> chore: move to Ruff-format

- .pre-commit-config.yaml
- pyproject.toml
- tests/__init__.py
- tests/test_setup.py
> chore: update ruff and fix warnings

- .pre-commit-config.yaml
- skbuild/command/sdist.py
- skbuild/setuptools_wrap.py
> chore: fix mypy type ignores for new setuptools types

- .github/workflows/ci.yml
Getting green checkmarks (minus Fedora now, I think).
> ci: skip win PyPy PEP 518

- .distro/python-scikit-build.spec
- .packit.yaml
A bit of maintenance similar to https://github.com/scikit-build/scikit-build-core/pull/689. No need for a new release or anything
> ci: Fedora maintenance

- .github/workflows/ci.yml
- noxfile.py
- pyproject.toml
> ci: use uv in a few places

- CHANGES.rst
Might do a little more cleanup, but probably close.
> docs: changelog for 0.18.0

- tests/__init__.py
> tests: fix for distutils change

- .github/workflows/ci.yml
- skbuild/command/bdist_wheel.py
- skbuild/platform_specifics/windows.py
- tests/test_issue284_build_ext_inplace.py
Fix #1114. Also would fix https://github.com/pypa/setuptools/issues/4608.
> fix: setuptools 74 support

- .github/workflows/ci.yml
- skbuild/command/build_py.py
- skbuild/platform_specifics/windows.py
- skbuild/setuptools_wrap.py
- tests/__init__.py
Fix #1119. Looks like it's only an issue with our tests.
> fix(types): Update for newer setuptools
